# Generated by Django 3.1.5 on 2021-02-17 19:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210212_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_path, verbose_name='Image'),
        ),
    ]
