# Generated by Django 3.1.5 on 2021-03-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('style', models.CharField(max_length=1)),
                ('summary', models.TextField(max_length=1000)),
            ],
        ),
    ]
