# Generated by Django 3.1.5 on 2021-03-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='powerwashed',
            field=models.BooleanField(default=False),
        ),
    ]
